name: 'build::subgraph'

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  build:
    strategy:
      max-parallel: 4
      matrix:
        manifest: [subgraph.kurtosis.yaml, subgraph.testnet_fast.yaml, subgraph.testnet.yaml, subgraph.devnet.yaml, subgraph.goerli_fast.yaml, subgraph.goerli.yaml, subgraph.mainnet_fast.yaml, subgraph.mainnet.yaml]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 'asdf:install'
        uses: asdf-vm/actions/install@v1.1.0

      - name: 'yarn:init'
        run: yarn

      - name: "graph:codegen for ${{matrix.manifest}}"
        run: $(yarn bin)/graph codegen ${{matrix.manifest}}

      - name: "graph:build for ${{matrix.manifest}}"
        run: $(yarn bin)/graph build ${{matrix.manifest}}

