name: 'deploy::subgraph'

on:
  push:
    branches:
      - master
    tags:
      - '*'
  release:
    types: [published]

permissions:
  id-token: write
  contents: read

jobs:

  deploy-devnet:
    runs-on: thegraph-devnet
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 'asdf:install'
        uses: asdf-vm/actions/install@v1.1.0
      - name: 'yarn:init'
        run: yarn

      # Deploy fast syncing goerli version
      - name: 'graph:codegen:goerli'
        run: $(yarn bin)/graph codegen subgraph.goerli_fast.yaml
      - name: 'graph:create:goerli'
        run: $(yarn bin)/graph create vsuite-goerli --node http://graph-node-query:8020
      - name: 'graph:deploy:goerli'
        run: $(yarn bin)/graph deploy vsuite-goerli --version-label ${GITHUB_REF##*/} --node http://graph-node-query:8020 --ipfs http://ipfs-ipfs:5001 subgraph.goerli_fast.yaml

      - name: 'graph:clean'
        run: $(yarn bin)/graph clean

      # Deploy slow syncing goerli version
      - name: 'graph:codegen:goerli-complete'
        run: $(yarn bin)/graph codegen subgraph.goerli.yaml
      - name: 'graph:create:goerli-complete'
        run: $(yarn bin)/graph create vsuite-goerli-complete --node http://graph-node-query:8020
      - name: 'graph:deploy:goerli-complete'
        run: $(yarn bin)/graph deploy vsuite-goerli-complete --version-label ${GITHUB_REF##*/} --node http://graph-node-query:8020 --ipfs http://ipfs-ipfs:5001 subgraph.goerli.yaml

      - name: 'graph:clean'
        run: $(yarn bin)/graph clean

      # Deploy fast syncing devnet
      - name: 'graph:codegen:devnet'
        run: $(yarn bin)/graph codegen subgraph.devnet_fast.yaml
      - name: 'graph:create:devnet'
        run: $(yarn bin)/graph create vsuite --node http://graph-node-query:8020
      - name: 'graph:deploy:devnet'
        run: $(yarn bin)/graph deploy vsuite --version-label ${GITHUB_REF##*/} --node http://graph-node-query:8020 --ipfs http://ipfs-ipfs:5001 subgraph.devnet_fast.yaml

      - name: 'graph:clean'
        run: $(yarn bin)/graph clean

      # Deploy slow syncing devnet version
      - name: 'graph:codegen:devnet-complete'
        run: $(yarn bin)/graph codegen subgraph.devnet.yaml
      - name: 'graph:create:devnet-complete'
        run: $(yarn bin)/graph create vsuite-complete --node http://graph-node-query:8020
      - name: 'graph:deploy:devnet-complete'
        run: $(yarn bin)/graph deploy vsuite-complete --version-label ${GITHUB_REF##*/} --node http://graph-node-query:8020 --ipfs http://ipfs-ipfs:5001 subgraph.devnet.yaml

  deploy-testnet:
    runs-on: thegraph-testnet
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 'asdf:install'
        uses: asdf-vm/actions/install@v1.1.0
      - name: 'yarn:init'
        run: yarn

      # Deploy fast syncing goerli version
      - name: 'graph:codegen:goerli'
        run: $(yarn bin)/graph codegen subgraph.goerli_fast.yaml
      - name: 'graph:create:goerli'
        run: $(yarn bin)/graph create vsuite-goerli --node http://graph-node-query:8020
      - name: 'graph:deploy:goerli'
        run: $(yarn bin)/graph deploy vsuite-goerli --version-label ${GITHUB_REF##*/} --node http://graph-node-query:8020 --ipfs http://ipfs-ipfs:5001 subgraph.goerli_fast.yaml

      - name: 'graph:clean'
        run: $(yarn bin)/graph clean

      # Deploy slow syncing goerli version
      - name: 'graph:codegen:goerli-complete'
        run: $(yarn bin)/graph codegen subgraph.goerli.yaml
      - name: 'graph:create:goerli-complete'
        run: $(yarn bin)/graph create vsuite-goerli-complete --node http://graph-node-query:8020
      - name: 'graph:deploy:goerli-complete'
        run: $(yarn bin)/graph deploy vsuite-goerli-complete --version-label ${GITHUB_REF##*/} --node http://graph-node-query:8020 --ipfs http://ipfs-ipfs:5001 subgraph.goerli.yaml

      # Deploy fast syncing testnet version
      - name: 'graph:codegen:testnet'
        run: $(yarn bin)/graph codegen subgraph.testnet_fast.yaml
      - name: 'graph:create:testnet'
        run: $(yarn bin)/graph create vsuite --node http://graph-node-query:8020
      - name: 'graph:deploy:testnet'
        run: $(yarn bin)/graph deploy vsuite --version-label ${GITHUB_REF##*/} --node http://graph-node-query:8020 --ipfs http://ipfs-ipfs:5001 subgraph.testnet_fast.yaml

      - name: 'graph:clean'
        run: $(yarn bin)/graph clean

      # Deploy slow syncing testnet version
      - name: 'graph:codegen:testnet-complete'
        run: $(yarn bin)/graph codegen subgraph.testnet.yaml
      - name: 'graph:create:testnet-complete'
        run: $(yarn bin)/graph create vsuite-complete --node http://graph-node-query:8020
      - name: 'graph:deploy:testnet-complete'
        run: $(yarn bin)/graph deploy vsuite-complete --version-label ${GITHUB_REF##*/} --node http://graph-node-query:8020 --ipfs http://ipfs-ipfs:5001 subgraph.testnet.yaml

  deploy-mainnet:
    runs-on: thegraph-mainnet
    if: github.event_name == 'release'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 'asdf:install'
        uses: asdf-vm/actions/install@v1.1.0
      - name: 'yarn:init'
        run: yarn

      # Deploy fast syncing mainnet version
      - name: 'graph:codegen:mainnet'
        run: $(yarn bin)/graph codegen subgraph.mainnet_fast.yaml
      - name: 'graph:create:mainnet'
        run: $(yarn bin)/graph create vsuite --node http://graph-node-query:8020
      - name: 'graph:deploy:mainnet'
        run: $(yarn bin)/graph deploy vsuite --version-label ${GITHUB_REF##*/} --node http://graph-node-query:8020 --ipfs http://ipfs-ipfs:5001 subgraph.mainnet_fast.yaml

      - name: 'graph:clean'
        run: $(yarn bin)/graph clean

      # Deploy slow syncing mainnet version
      - name: 'graph:codegen:mainnet-complete'
        run: $(yarn bin)/graph codegen subgraph.mainnet.yaml
      - name: 'graph:create:mainnet-complete'
        run: $(yarn bin)/graph create vsuite-complete --node http://graph-node-query:8020
      - name: 'graph:deploy:mainnet-complete'
        run: $(yarn bin)/graph deploy vsuite-complete --version-label ${GITHUB_REF##*/} --node http://graph-node-query:8020 --ipfs http://ipfs-ipfs:5001 subgraph.mainnet.yaml
