name: 'deploy::subgraph'

on:
  push:
    tags:
      - '*'

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: vsuite
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 'asdf:install'
        uses: asdf-vm/actions/install@v1.1.0

      - name: 'yarn:init'
        run: yarn

      - name: 'graph:codgen'
        run: $(yarn bin)/graph codegen

      - name: 'graph:create'
        run: $(yarn bin)/graph create vsuite-goerli-audit --node http://graph-node-query.thegraph:8020

      - name: 'graph:deploy'
        run: $(yarn bin)/graph deploy vsuite-goerli-audit --version-label ${{ github.ref_name }} --node http://graph-node-query.thegraph:8020 --ipfs http://ipfs-ipfs.thegraph:5001
