name: 'deploy::subgraph'

on:
  push:
    tags:
      - '*'

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: vsuite
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 'asdf:install'
        uses: asdf-vm/actions/install@v1.1.0

      - name: 'graph:install'
        run: |
          yarn global add @graphprotocol/graph-cli@0.40.0

      - name: 'yarn-npm:init'
        run: |
          yarn
          npm install

      - name: 'graph:codgen'
        run: |
          $(yarn global bin)/graph codegen

      - name: 'graph:deploy'
        run: |
          $(yarn global bin)/graph deploy vsuite-goerli --version-label ${{ github.ref_name }} --node http://graph-node-query.thegraph:8020 --ipfs http://ipfs-ipfs.thegraph:5001
